spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 # how many request  it has to monitor before chaning status from close to open
        permitted-number-of-calls-in-half-open-state: 2 # number of requests are allow in half open state - to decide to go to open or close state
        failure-rate-threshold: 50 # in percentage - if the 50% of requests are faild then move to open state
        wait-duration-in-open-state: 10000 # in milliseconds - wait 10 seconds before goining into halfopen state

